// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20250622170416_SeedmoreEnclosures")]
    partial class SeedmoreEnclosures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalSize")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Diet")
                        .HasColumnType("int");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("activityPattern")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalSize = 0,
                            CategoryId = 12,
                            Diet = 0,
                            Name = "Leeuw",
                            Prey = "Gazelle",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Panthera leo",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 2,
                            AnimalSize = 0,
                            CategoryId = 13,
                            Diet = 0,
                            Name = "Olifant",
                            Prey = "Planten",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Loxodonta africana",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 3,
                            AnimalSize = 0,
                            CategoryId = 2,
                            Diet = 0,
                            Name = "Papegaai",
                            Prey = "Zaden",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Ara ararauna",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 4,
                            AnimalSize = 0,
                            CategoryId = 3,
                            Diet = 0,
                            Name = "Boa",
                            Prey = "Knaagdieren",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Boa constrictor",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 5,
                            AnimalSize = 0,
                            CategoryId = 4,
                            Diet = 0,
                            Name = "Kikker",
                            Prey = "Insecten",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Rana temporaria",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 6,
                            AnimalSize = 0,
                            CategoryId = 5,
                            Diet = 0,
                            Name = "Goudvis",
                            Prey = "Algen",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Carassius auratus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 7,
                            AnimalSize = 0,
                            CategoryId = 6,
                            Diet = 0,
                            Name = "Vlinder",
                            Prey = "Nectar",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Danaus plexippus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 8,
                            AnimalSize = 0,
                            CategoryId = 7,
                            Diet = 0,
                            Name = "Kreeft",
                            Prey = "Detritus",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Homarus gammarus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 9,
                            AnimalSize = 0,
                            CategoryId = 8,
                            Diet = 0,
                            Name = "Inktvis",
                            Prey = "Visjes",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Octopus vulgaris",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 10,
                            AnimalSize = 0,
                            CategoryId = 2,
                            Diet = 0,
                            Name = "Oehoe",
                            Prey = "Muizen",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Bubo bubo",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 11,
                            AnimalSize = 0,
                            CategoryId = 2,
                            Diet = 0,
                            Name = "Pinguïn",
                            Prey = "Vis",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Aptenodytes forsteri",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 12,
                            AnimalSize = 0,
                            CategoryId = 13,
                            Diet = 0,
                            Name = "Giraffe",
                            Prey = "Bladeren",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Giraffa camelopardalis",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 13,
                            AnimalSize = 0,
                            CategoryId = 15,
                            Diet = 0,
                            Name = "Chimpansee",
                            Prey = "Fruit",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Pan troglodytes",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 14,
                            AnimalSize = 0,
                            CategoryId = 17,
                            Diet = 0,
                            Name = "Walvis",
                            Prey = "Krill",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Balaenoptera musculus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 15,
                            AnimalSize = 0,
                            CategoryId = 18,
                            Diet = 0,
                            Name = "Vleermuis",
                            Prey = "Insecten",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Myotis myotis",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 16,
                            AnimalSize = 0,
                            CategoryId = 19,
                            Diet = 0,
                            Name = "Muis",
                            Prey = "Zaden",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Mus musculus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 17,
                            AnimalSize = 0,
                            CategoryId = 20,
                            Diet = 0,
                            Name = "Hert",
                            Prey = "Planten",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Cervus elaphus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 18,
                            AnimalSize = 0,
                            CategoryId = 20,
                            Diet = 0,
                            Name = "Koe",
                            Prey = "Gras",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Bos taurus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 19,
                            AnimalSize = 0,
                            CategoryId = 12,
                            Diet = 0,
                            Name = "Wolf",
                            Prey = "Herten",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Canis lupus",
                            activityPattern = 0
                        },
                        new
                        {
                            Id = 20,
                            AnimalSize = 0,
                            CategoryId = 2,
                            Diet = 0,
                            Name = "Eend",
                            Prey = "Kleine vis",
                            SecurityRequirement = 0,
                            SpaceRequirement = 0.0,
                            Species = "Anas platyrhynchos",
                            activityPattern = 0
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Zoogdieren"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vogels"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reptielen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amfibieën"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vissen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Insecten"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Schaaldieren"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Weekdieren"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kringloopdieren"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Buideldieren"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pinnipedia"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Carnivoren"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Herbivoren"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Omnivoren"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Primaten"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Carnivora"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cetacea"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Chiroptera"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Rodentia"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Artiodactyla"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Habitat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.Property<int>("securityLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Climate = 0,
                            Description = "Large grassland area for African animals.",
                            Habitat = 3,
                            Name = "Savannah Zone",
                            Size = 1200.5,
                            securityLevel = 1
                        },
                        new
                        {
                            Id = 102,
                            Climate = 2,
                            Description = "Cold environment for penguins.",
                            Habitat = 1,
                            Name = "Penguin Cove",
                            Size = 800.0,
                            securityLevel = 2
                        },
                        new
                        {
                            Id = 103,
                            Climate = 0,
                            Description = "Hot and dry enclosure for desert species.",
                            Habitat = 2,
                            Name = "Desert Dunes",
                            Size = 600.0,
                            securityLevel = 0
                        },
                        new
                        {
                            Id = 104,
                            Climate = 0,
                            Description = "Dense forest area for tropical animals.",
                            Habitat = 0,
                            Name = "Rainforest Retreat",
                            Size = 950.0,
                            securityLevel = 1
                        },
                        new
                        {
                            Id = 105,
                            Climate = 2,
                            Description = "Chilly area for polar bears and arctic foxes.",
                            Habitat = 3,
                            Name = "Arctic Tundra",
                            Size = 1100.0,
                            securityLevel = 2
                        },
                        new
                        {
                            Id = 106,
                            Climate = 0,
                            Description = "Lush forest enclosure for monkeys and birds.",
                            Habitat = 0,
                            Name = "Jungle Jump",
                            Size = 720.0,
                            securityLevel = 1
                        },
                        new
                        {
                            Id = 107,
                            Climate = 1,
                            Description = "Open space for giraffes and zebras.",
                            Habitat = 3,
                            Name = "Giraffe Plains",
                            Size = 1300.0,
                            securityLevel = 0
                        },
                        new
                        {
                            Id = 108,
                            Climate = 0,
                            Description = "Watery habitat for crocodiles.",
                            Habitat = 1,
                            Name = "Crocodile Creek",
                            Size = 500.0,
                            securityLevel = 2
                        },
                        new
                        {
                            Id = 109,
                            Climate = 1,
                            Description = "Sheltered desert oasis for camels and reptiles.",
                            Habitat = 2,
                            Name = "Oasis Haven",
                            Size = 780.0,
                            securityLevel = 1
                        },
                        new
                        {
                            Id = 110,
                            Climate = 1,
                            Description = "Mild climate zone for deer and small mammals.",
                            Habitat = 3,
                            Name = "Temperate Trails",
                            Size = 850.0,
                            securityLevel = 0
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Zoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zoos");
                });

            modelBuilder.Entity("WebApplication1.Models.Animal", b =>
                {
                    b.HasOne("WebApplication1.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId");

                    b.HasOne("WebApplication1.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId");

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("WebApplication1.Models.Enclosure", b =>
                {
                    b.HasOne("WebApplication1.Models.Zoo", null)
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId");
                });

            modelBuilder.Entity("WebApplication1.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("WebApplication1.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("WebApplication1.Models.Zoo", b =>
                {
                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
